version: "3.3"

services:

  node-service:
    build:
      context: node
    container_name: node-service
    entrypoint: wait-for mysql-service:3306 -t 40 -- ./start.sh
    networks:
      - rede-principal
    tty: true
    ports:
      - "3000"
    depends_on:
      - mysql-service

  mysql-service:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: mysql-service
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - rede-principal
    ports:
      - "3306"
  
  nginx-service:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx-service
    networks:
      - rede-principal
    ports:
      - "8080:80"
    depends_on:
      - node-service

networks:
  rede-principal:
    driver: bridge
